name: tic_tac_touch
description: A simple Tic-Tac-Toe game.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  flutter_launcher_icons: ^0.13.1

  flutter_native_splash: ^2.3.2

flutter:
  uses-material-design: true

  assets:
    - assets/images/
  
  fonts:
    - family: Bangers
      fonts:
        - asset: assets/fonts/Bangers-Regular.ttf

flutter_launcher_icons:
  android: true
  image_path: assets/images/icon.png
  adaptive_icon_background: assets/images/background.png
  adaptive_icon_foreground: assets/images/icon.png

flutter_native_splash:
  android: true
  color: "#222222"
  color_dark: "#222222"
  image: assets/images/icon.png
  image_dark: assets/images/icon.png
  android_12:
    image: assets/images/icon.png
    image_dark: assets/images/icon.png
